jobs:
- job: Build
  displayName: Build
  pool:
    vmImage: $(vmImageName)
  steps:
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: |
        $(tag)

- job: Deploy
  displayName: Deploy- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'MSDN Platforms Subscription(4)(bd3dc7c5-5972-4972-9e57-dac495e3e51e)'
    azureResourceGroup: 'AKS'
    kubernetesCluster: 'AKScluster'
    useClusterAdmin: true
  pool:
    vmImage: $(vmImageName)
  steps:
  - task: KubernetesManifest@1
    displayName: Deploy to Azure Kubernetes Service
    inputs:
      action: 'deploy'
      connectionType: 'azureResourceManager'
      azureSubscriptionConnection: 'MSDN Platforms Subscription(3)(bd3dc7c5-5972-4972-9e57-dac495e3e51e)'
      azureResourceGroup: 'AKS'
      kubernetesCluster: 'AKScluster'

  - task: KubernetesManifest@1
    displayName: Deploy to Azure Kubernetes Service
    inputs:
      action: 'deploy'
      connectionType: 'azureResourceManager'
      azureSubscriptionConnection: 'MSDN Platforms Subscription(2)(bd3dc7c5-5972-4972-9e57-dac495e3e51e)'
      azureResourceGroup: 'AKS'
      kubernetesCluster: 'AKScluster'
      namespace: 'Adoapp'
